name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "devlopment" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET 6 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore projects
      run: dotnet restore
    - name: Build projects
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal